---
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dsvw
  name: dsvw
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsvw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dsvw
    spec:
      containers:
      - image: porcer/pcc-dsvw
        name: dsvw
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dsvw
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - name: web
    targetPort: 80
    port: 80
  selector:
    app: dsvw
